spring.datasource.name=food

spring.datasource.url=jdbc:postgresql://localhost:5432/food
spring.datasource.username=postgres
spring.datasource.password=58255825

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# ===== Admin Credentials (In-Memory) =====
admin.email=admin@foodfrenzy.com
admin.password=admin123

# ===== Session Config =====
server.servlet.session.timeout=30m

# ===== Cloudinary Configuration =====
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
