spring.datasource.name=food

spring.datasource.name=${DB_NAME}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.jpa.hibernate.ddl-auto=update

# ===== Admin Credentials =====
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}

# ===== Session Config =====
server.servlet.session.timeout=${SESSION_TIMEOUT}

# ===== Cloudinary Configuration =====
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
